### ISSUE TITLE
Nome do diretório está errado

### ISSUE THREAD

**Issue by diogomoreira** [recursivejr/ecmat-webapp#1]
O nome do diretório da aplicação está "ecmat-webbapp" (com dois B).

Como sugestão, eu deixaria só "webapp", uma vez que ele está dentro do repositório "ecmat-webapp" acaba ficando redundante.

**Comment by douglasgabriel** [comment]
O ruim seria identificá-lo em uma IDE, por exemplo

**Comment by douglasgabriel** [comment]
Já que a intenção é que a aplicação seja utilizada para outros eventos, então mudei o nome para event-webapp
